name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Download Licenses
        run: ./gradlew downloadLicenses
        working-directory: ./game
      - name: Copy License Files
        run: cp game/core/build/reports/license/license-dependency.json website/public/core-license-dependency.json && cp game/lwjgl3/build/reports/license/license-dependency.json website/public/lwjgl3-license-dependency.json

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: website

      - name: Build project
        working-directory: ./website
        run: npm run build

      - name: Add CNAME for deployment
        run: |
          touch website/dist/CNAME
          echo "eng1.archess.mn" >> website/dist/CNAME

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./website/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
